# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: codelab
    foo: bar

scrape_configs:
  - job_name: prometheus

    honor_labels: true
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
  - job_name: node
    static_configs:
    - targets: ['localhost:9100']

  # - job_name: linode-instances
  #   linode_sd_configs:
  #     - authorization:
  #         credentials: op://Private/Linode API Access Token/password